Accepted two patches from Ike - 3-finger claw infra and requirements testing for nftblocklist

diff --git a/nftblocklist b/nftblocklist
--- a/nftblocklist
+++ b/nftblocklist
@@ -1,8 +1,18 @@
 #!/bin/bash
 
+yell() { echo "$0: $*" >&2; }
+die() { yell "$*"; exit 111; }
+try() { "$@" || die "cannot $*"; }
+
 # nftblocklist - a script to manage dynamic and persistent IP blocklists using nftables.
 #
 #   Requirements:  nftables, iprange, jq, json_pp 
+
+_requirements="nft iprange jq json_pp awk tr grep"
+
+for i in `echo "${_requirements}"` ; do
+  try which "${i}" >> /dev/null
+done
 
 
 ## Default values
@@ -169,3 +179,4 @@ done
 echo "done!"
 exit
 
+true
diff --git a/nftblocklistload b/nftblocklistload
--- a/nftblocklistload
+++ b/nftblocklistload
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+yell() { echo "$0: $*" >&2; }
+die() { yell "$*"; exit 111; }
+try() { "$@" || die "cannot $*"; }
 
 export FILE_LOCATION="/etc/nftables.blocklist"
 export TARGET_SET="blocklist_persist"
@@ -17,3 +20,5 @@ fi
 nft flush set inet filter $TARGET_SET
 
 echo add element inet filter $TARGET_SET { $(awk '{print $1 ", "}' $FILE_LOCATION) } | nft -f -
+
+true
