Fixed option handling; added infile and outfile options

diff --git a/nftblocklist b/nftblocklist
--- a/nftblocklist
+++ b/nftblocklist
@@ -24,6 +24,9 @@ export CONFIG_LOCATION="/etc/nftables.conf"
 # Default persistent blocklist file location
 export BLOCKLIST_LOCATION="/etc/nftables.blocklist"
 
+# Locaiton of blocklist to load/combine
+export BLOCKLIST_INPUT=$BLOCKLIST_LOCATION
+
 # Default manual blocklist input file location
 export BLOCKLIST_OVERRIDE_LOCATION="/etc/nftables.blockcidrs"
 
@@ -90,12 +93,19 @@ dump()
     try /usr/sbin/nft -j list ruleset | \
     try /usr/bin/json_pp | \
     try /usr/bin/jq '.[]|.[]|.[]| select(.name=="'$BLOCKLIST_DYN_SET'")|.elem' | \
-    try /usr/bin/grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | cat > $BLOCKLIST_TMP_LOCATION
+    try /usr/bin/grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' > $BLOCKLIST_TMP_LOCATION
 
-    log 6 "Combining existing blocklist and manual ranges, then optimizing..."
+    log 6 "Combining existing blocklist and manual ranges..."
 
-    # Append the current blocklist file contents
-    try cat $BLOCKLIST_LOCATION >> $BLOCKLIST_TMP_LOCATION
+    # Append the current blocklist file contents if it exists at $BLOCKLIST_LOCATION
+    if [ -e $BLOCKLIST_INPUT ]; then
+        try cat $BLOCKLIST_INPUT >> $BLOCKLIST_TMP_LOCATION
+    else
+	log 3 "Input blocklist file not found!"
+	exit 1
+    fi
+
+    log 6 "Dedup and optimitizing blocklist ranges..."
 
     # Use iprange to merge and optimize the list, and include the manual file if it exists
     if [ -e $BLOCKLIST_OVERRIDE_LOCATION ]; then
@@ -105,6 +115,7 @@ dump()
     fi
 
     # Clean up
+    log 6 "Cleaning up temp files..."
     try /bin/rm -f $BLOCKLIST_TMP_LOCATION
 
     log 6 "Blocklist dump and optimize complete! New blocklist saved to $BLOCKLIST_LOCATION"
@@ -145,11 +156,15 @@ done
 log 6 "Verbosity level set to $VERBOSITY"
 
 OPTIND=0
-while getopts ":h:f:sdlrnv:" opt; do
+while getopts ":o:i:s:hdlrnv:" opt; do
   case ${opt} in
-    f)
+    o)
       export BLOCKLIST_LOCATION=${OPTARG}
-      log 7 "Blocklist file location: $BLOCKLIST_LOCATION"
+      log 7 "Blocklist output file location: $BLOCKLIST_LOCATION"
+      ;;
+    i)
+      export BLOCKLIST_INPUT=${OPTARG}
+      log 7 "Blocklist input file location: $BLOCKLIST_INPUT"
       ;;
     s)
       export BLOCKLIST_PERSISTENT_SET=${OPTARG}
@@ -172,6 +187,8 @@ while getopts ":h:f:sdlrnv:" opt; do
     n)
       # Null - do nothing
       log 6 "Null action option detected!"
+      log 7 "Current environment (variables) are:"
+      log 7 $(env) 
       exit;;
     v)
       # we've already processed these above, ignore
@@ -187,7 +204,7 @@ while getopts ":h:f:sdlrnv:" opt; do
   esac
 done
 
-echo "done!"
+log 6  "done!"
 exit
 
 true
